### ISSUE TITLE
Database template page link is locked

### ISSUE THREAD

**Issue by Vicente015** [younho9/notion2github#2]
Hey! 👋 
I like your project and I'm testing it :)
The [database template page for tests](https://github.com/younho9/notion2github#database-template-page-for-test) from the README is locked.

![image](https://user-images.githubusercontent.com/33096355/101664493-d1ae1a00-3a43-11eb-8958-07151a37e6a1.png)

**Comment by younho9** [comment]
Hi! 👋
Thanks for your interest and reporting the problem! 👍 
I have modified the sharing options in notion, so you can access and duplicate [database template](https://www.notion.so/acc3dfd0339e4cacb5baae8673fddfad?v=be43c1c8dd644cfb9df9efd97d8af60a)!

**Comment by Vicente015** [comment]
Thank you!
